{
 "title": "Redis Clusters 监控",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(redis_up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "客户端连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(redis_connected_clients{job=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}-hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}-misses"
    }
   ]
  },
  {
   "title": "redis status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{job=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis role",
   "type": "piechart",
   "description": "1 master\n0 slave",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_slaves{job=\"$cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "过期与未过期的key",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=\"$cluster\"}) - sum (redis_db_keys_expiring{job=\"$cluster\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=\"$cluster\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "每个DB下所有的key",
   "type": "graph",
   "description": "Total number of keys by DB.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=\"$cluster\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}-input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}-output"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"$cluster\"} ",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "redis_config_maxmemory{job=\"$cluster\"} ",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "redis cpu used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(redis_cpu_sys_seconds_total[2m]) + rate(redis_cpu_user_seconds_total[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "description": "The number of calls that reached command execution (not rejected).(Counter)\n达到命令执行的调用次数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{job=\"$cluster\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "description": "redis_evicted_keys_total: Number of evicted keys due to maxmemory limit.(Counter)\nredis_expired_keys_total: Total number of key expiration events.(Counter)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=\"$cluster\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}--expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=\"$cluster\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}--evicted"
    }
   ]
  },
  {
   "title": "Redis Aof Duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(redis_aof_last_rewrite_duration_sec{job=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "description": "服务处理命令的总数,其命令都是从一个或多个Redis客户端请求过来的",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=\"$cluster\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}