{
 "title": "集群监控 - 总览信息",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node_label",
    "label": "node_label",
    "query": {
     "query": "label_values(node_load1{job=\"node-exporter-discovery\"}, nodetype)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "node_load1{job=\"node-exporter-discovery\", nodetype=~\"$node_label\"}"
    }
   },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_pod_container_info{},namespace)"
    }
   },
   {
    "name": "container",
    "label": "应用",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{container=~\"$container\"},pod)"
    }
   },
   {
    "name": "unschedulable_node",
    "label": "unschedulable_node",
    "query": {
     "query": "query_result(kube_node_spec_unschedulable{}==1)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "集群使用及分配监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "集群$node_label节点CPU容量（capacity）",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",job=\"kube-state-metrics\"})",
     "legendFormat": "$env"
    }
   ]
  },
  {
   "title": "$node_label 节点内存容量（capacity）",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "集群$node_label 节点pod cpu已使用核数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate(container_cpu_usage_seconds_total{container !=\"\"}[2m])) by (pod))"
    }
   ]
  },
  {
   "title": "集群$node_label节点pod已使用内存",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\"}) by (pod) /1024/1024/1024)"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "gauge",
   "description": " 集群节点cpu使用率",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\",job=\"node-exporter-discovery\",nodetype=~\"$node_label\"}[2m])) / sum(kube_node_status_capacity{resource=\"cpu\",job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "description": "已经使用内存 / 所有内存",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{nodetype=~\"$node_label\"}) - sum(node_memory_MemFree_bytes{nodetype=~\"$node_label\"} + node_memory_Buffers_bytes{nodetype=~\"$node_label\"}+node_memory_Cached_bytes{nodetype=~\"$node_label\"}))/sum(node_memory_MemTotal_bytes{nodetype=~\"$node_label\"}) * 100"
    }
   ]
  },
  {
   "title": "$node_label 节点数量",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info{})", "legendFormat": " 总节点数" },
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"unknown\"} >0)",
     "legendFormat": "NotReady 节点数"
    }
   ]
  },
  {
   "title": "集群$node_label节点已分配资源",
   "type": "bargauge",
   "description": "k8s 集群分配资源，就是requests资源",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\",node=~\".*-$node_label-.*\"})/sum(kube_node_status_capacity{resource=\"cpu\",job=\"kube-state-metrics\",node=~\".*-$node_label-.*\"})*100",
     "legendFormat": "CPU Allocated"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",node=~\".*-$node_label-.*\"})/sum(kube_node_status_capacity{resource=\"memory\",job=\"kube-state-metrics\",node=~\".*-$node_label-.*\"})*100",
     "legendFormat": "Memory Alllocated "
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{nodetype=~\"$node_label\"}-node_memory_MemAvailable_bytes{nodetype=~\"$node_label\"}) / sum(kube_node_status_capacity{resource=\"memory\"}) ",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(1-avg(irate(node_cpu_seconds_total{mode=\"idle\",nodetype=~\"$node_label\"}[2m])) by (instance))",
     "legendFormat": "CPU  Usage （2m）"
    }
   ]
  },
  {
   "title": "Mem Allocate By $node_label 节点",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",job=\"kube-state-metrics\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",job=\"kube-state-metrics\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",job=\"kube-state-metrics\"})",
     "legendFormat": "allocatable"
    }
   ]
  },
  {
   "title": "CPU Allocated By $node_label 节点",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",job=\"kube-state-metrics\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",job=\"kube-state-metrics\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",job=\"kube-state-metrics\"})",
     "legendFormat": "allocatable"
    }
   ]
  },
  {
   "title": "$node_label 节点总 Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{nodetype=~\"$node_label\"}-node_memory_MemAvailable_bytes{nodetype=~\"$node_label\"}) / sum(kube_node_status_capacity{resource=\"memory\"}) ",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "$node_label 节点 cpu 总使用率（1m）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(1-avg(rate(node_cpu_seconds_total{mode=\"idle\",nodetype=~\"$node_label\"}[1m])) by (instance))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "$node_label  节点 cpu 已分配资源 Top 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\"}) by (node)/sum(kube_node_status_allocatable{resource=\"cpu\",job=\"kube-state-metrics\"}) by (node)*100))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node_label  节点 Mem 已分配资源  Top 10",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\"}) by (node)/sum(kube_node_status_allocatable{resource=\"memory\",job=\"kube-state-metrics\"}) by (node)*100))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node_label 节点 Load5  Top 10（node）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10,node_load15{job=\"node-exporter-discovery\",nodetype=~\"$node_label\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "${node_label} 节点 CPU  使用 Top 10（node）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10,100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-discovery\",nodetype=~\"$node_label\"}[5m])) * 100)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node_label 节点 Mem Usage Top 10（node）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10,100 - sum((node_memory_MemFree_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\"}+node_memory_Cached_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\"}+node_memory_Buffers_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\"})/node_memory_MemTotal_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\"})by (instance)*100))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node_label 节点 Disk Usage Top 10（node）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, (1 - (node_filesystem_avail_bytes{mountpoint=~\"/data.*|/\",job=\"node-exporter-discovery\",nodetype=~\"$node_label\"} / node_filesystem_size_bytes{mountpoint=~\"/data.*|/\",job=\"node-exporter-discovery\",nodetype=~\"$node_label\"})) *100))",
     "legendFormat": "{{instance}}--{{mountpoint}}"
    }
   ]
  },
  {
   "title": "主机监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pod 数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10,count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"$node\"}) by (node)))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "磁盘大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"^/dev/.*\",mountpoint!~\"/boot|/boot/efi\",instance=~\"$node\"}/1024/1024/1024",
     "legendFormat": "Total--{{mountpoint}}--{{device}}"
    },
    {
     "expr": "node_filesystem_free_bytes{device=~\"^/dev/.*\",mountpoint!~\"/boot|/boot/efi\",instance=~\"$node\"}/1024/1024/1024",
     "legendFormat": "Free--{{mountpoint}}--{{device}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_avail_bytes{device=~\"^/dev/.*\",mountpoint!~\"/boot|/boot/efi\",instance=~\"$node\"} / node_filesystem_size_bytes{device=~\"^/dev/.*\",mountpoint!~\"/boot|/boot/efi\",instance=~\"$node\"})",
     "legendFormat": "Usage--{{mountpoint}}--{{device}}"
    },
    {
     "expr": "node_filesystem_files_free{device=~\"^/dev/.*\",mountpoint!~\"/boot|/boot/efi\",instance=~\"$node\"} / node_filesystem_files{device=~\"^/dev/.*\",mountpoint!~\"/boot|/boot/efi\",instance=~\"$node\"}",
     "legendFormat": "Inodes--{{mountpoint}}--{{device}}"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "TCP 连接状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 43 },
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$node\",state!~\"^tx_.*|^^rx_.*\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Resource Allocated (request/Alllocated)",
   "type": "bargauge",
   "description": "k8s 集群分配资源，就是requests资源",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\",node=~\"$node\"})by (node)/sum(kube_node_status_allocatable{resource=\"cpu\",job=\"kube-state-metrics\",node=~\"$node\"})by (node) *100 ",
     "legendFormat": "CPU Allocated "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$node\"})by (node) /sum(kube_node_status_allocatable{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$node\"})by (node) *100 ",
     "legendFormat": "Memory Alllocated "
    },
    {
     "expr": "sum by (instance) (sum((node_memory_Active_file_bytes{job=\"node-exporter-discovery\",instance=~\"$node\"}+node_memory_Active_anon_bytes{job=\"node-exporter-discovery\",instance=~\"$node\"})) by (instance) / sum(node_memory_MemTotal_bytes{job=\"node-exporter-discovery\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Memory Usage "
    },
    {
     "expr": "avg(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-discovery\",nodetype=~\"$node_label\",instance=~\"$node\"}[2m])) * 100)) by (instance)",
     "legendFormat": "CPU Usage "
    }
   ]
  },
  {
   "title": "Memory Allocated ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}--capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}--Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}--Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}--allocatable"
    }
   ]
  },
  {
   "title": "CPU Allocate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}--capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"}) by(node)",
     "legendFormat": "{{node}}--Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",node=~\"$node\"}) by(node)",
     "legendFormat": "{{node}}--Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}--allocatable"
    }
   ]
  },
  {
   "title": "$node 主机cpu使用率(2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-discovery\",nodetype=~\"$node_label\",instance=~\"$node\"}[2m])) * 100)) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node 主机内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (sum((node_memory_Active_file_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\",instance=~\"$node\"}+node_memory_Active_anon_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\",instance=~\"$node\"})) by (instance) / sum(node_memory_MemTotal_bytes{job=\"node-exporter-discovery\",nodetype=~\"$node_label\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{  instance }}"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}--读取"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}--写入"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗费的时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{device}}_每秒I/O操作"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[2m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[2m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{device}}_写入"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{device}}-查询指定磁盘的每秒磁盘 io"
    }
   ]
  },
  {
   "title": "每秒磁盘读写速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}-读"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}-写"
    }
   ]
  },
  {
   "title": "命名空间维度",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu总体使用率占用比例",
   "type": "piechart",
   "description": "当前所有资源使用率加起来，以namespace分割",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg(rate(container_cpu_usage_seconds_total{container !=\"\",container != \"POD\"}[2m])) by(pod,container,namespace)) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "内存总体使用率占用比例",
   "type": "piechart",
   "description": "当前所有使用率namespace比例",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(sum(container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}) by (service,pod,namespace)) by (service,pod,namespace)) by (namespace) ",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "$namespace  ns下资源 整体cpu使用率",
   "type": "timeseries",
   "description": "实际使用资源",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace)(\n    avg(\n        rate(container_cpu_usage_seconds_total{container !=\"\",container != \"POD\",namespace=~\"$namespace\"}[5m])\n    ) by (namespace,container,pod)\n) /ignoring(namespace) group_left sum(kube_node_status_capacity{resource=\"cpu\",job=\"kube-state-metrics\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "$namespace  ns下资源 占用集群内存使用率",
   "type": "timeseries",
   "description": "实际使用资源",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg(sum(container_memory_working_set_bytes{container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (service,pod,namespace)) by (service,pod,namespace)) by (namespace) / ignoring(namespace) group_left sum(sum(kube_node_status_capacity{resource=\"memory\",job=\"kube-state-metrics\"})) * 100",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "$namespace cpu 分配率",
   "type": "timeseries",
   "description": "在k8s 集群中 resource request 资源",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\"}) by (namespace) / ignoring(namespace) group_left sum(kube_node_status_capacity{job=\"kube-state-metrics\",resource=\"cpu\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "$namespace 内存分配率",
   "type": "timeseries",
   "description": "resource request 资源",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}) by (namespace) / ignoring(namespace) group_left sum(kube_node_status_capacity{job=\"kube-state-metrics\",resource=\"memory\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "服务维度（根据namesapce筛选）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod QOS配置情况",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",container!=\"istio-proxy\",namespace=\"$namespace\",container!=\"\"}) by (pod) / 1024 / 1024 / 1024"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",container!=\"istio-proxy\",namespace=\"$namespace\",container!=\"\"}/1024/1024/1024) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",container!=\"istio-proxy\",namespace=\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",container!=\"istio-proxy\",namespace=\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\",image!=\"\"}[2m])) by (pod)",
     "legendFormat": "cpu 使用量"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\",namespace=~\"$namespace\"}) by (pod)/1024/1024/1024",
     "legendFormat": "内存用量"
    },
    {
     "expr": "max_over_time((sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"istio-proxy\"}[1m])) by (pods) / sum(kube_pod_container_resource_requests_cpu_cores{container!=\"istio-proxy\",container!=\"\"}) by (pods)) [24h:]) * 100"
    },
    {
     "expr": "max_over_time((sum(container_memory_working_set_bytes{container!=\"\",namespace=\"$namespace\"}) by (pods) / sum(kube_pod_container_resource_requests{resource=\"memory\",container!=\"\",namespace=\"$namespace\"}) by (pods)) [24h:]) * 100"
    }
   ]
  },
  {
   "title": "Pod CPU使用量(1m）",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\",image!=\"\",pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\",container=~\"$container\"}) by (pod)",
     "legendFormat": "curr-workingset--{{pod}}"
    },
    {
     "expr": "avg(container_memory_rss{pod=~\"$pod\", container!=\"POD\",container!=\"\",image!=\"\",container=~\"$container\"}) by (pod)",
     "legendFormat": "curr-RSS-{{pod}}"
    }
   ]
  },
  {
   "title": "pod 流入流量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])) by (pod,interface)",
     "legendFormat": "{{pod}}--接收"
    }
   ]
  },
  {
   "title": "pod 流出流量",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}---流出"
    }
   ]
  },
  {
   "title": "container 健康状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}--{{container}}"
    }
   ]
  },
  {
   "title": "pod 重启次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}