{
 "title": "节点监控信息",
 "description": "【中文版本】支持 Node Exporter v0.16及以上的版本，精简优化重要指标展示。包含：CPU 内存 磁盘 IO 网络 温度等监控指标。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Node_name",
    "label": "Node_name",
    "query": {
     "query": "label_values(node_load1{job=\"node-exporter-discovery\"},instance)"
    }
   },
   {
    "name": "host_ip",
    "label": "host_ip",
    "query": {
     "query": "label_values(node_load1{job=\"node-exporter-discovery\", instance =~\"$Node_name\"}, host_ip)"
    }
   },
   {
    "name": "NameSpace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{node =~\"$Node_name\"},namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{node =~\"$Node_name\",namespace=~\"$NameSpace\"},pod)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\",pod=~\"$Pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node 资源状态信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pod 数量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",host_ip=~\"$host_ip\"}) by (node)"
    }
   ]
  },
  {
   "title": "Mem Usage By Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_capacity{resource=\"memory\",node=~\"$Node_name\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\"$Node_name\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",node=~\"$Node_name\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cpu Usage By Node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_capacity{resource=\"cpu\",node=~\"$Node_name\"}",
     "legendFormat": "CPU 总核数"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$Node_name\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",node=~\"$Node_name\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$Node_name\",mode=\"system\"}[5m])) by (instance)",
     "legendFormat": "$host_ip-System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$Node_name\",mode=\"user\"}[5m])) by (instance)",
     "legendFormat": "$host_ip-User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$Node_name\",mode=\"iowait\"}[5m])) by (instance)",
     "legendFormat": "$host_ip-Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$Node_name\",mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "$host_ip-Used"
    }
   ]
  },
  {
   "title": "Disk Usage(G)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"^/dev/.*\",mountpoint!~\"^/boot.*\",instance=~\"$Node_name\"}",
     "legendFormat": "总大小：{{device}}-{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_free_bytes{device=~\"^/dev/.*\",mountpoint!~\"^/boot.*\",instance=~\"$Node_name\"}",
     "legendFormat": "未使用：{{device}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "分时磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_avail_bytes{instance=~\"$Node_name\",device=~\"^/dev.*\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"} / node_filesystem_size_bytes{instance=~\"$Node_name\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"})",
     "legendFormat": "disk_used——{{device}}-{{mountpoint}}"
    },
    {
     "expr": "1-(node_filesystem_files_free{instance=~\"$Node_name\",device=~\"^/dev.*\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"} / node_filesystem_files{instance=~\"$Node_name\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"})",
     "legendFormat": "Inodes_free：{{device}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$Node_name\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{host_ip}}_{{device}}_in  接收"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{instance=~\"$Node_name\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{host_ip}}_{{device}}_out 上传"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$Node_name\"}",
     "legendFormat": "{{host_ip}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$Node_name\"}",
     "legendFormat": "{{host_ip}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$Node_name\"}",
     "legendFormat": "{{host_ip}}_15m"
    }
   ]
  },
  {
   "title": "打开的文件描述符(左 )/每秒上下文切换次数(右)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$Node_name\"}",
     "legendFormat": "当前进程已经打开的文件描述符数量"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "每秒上下文切换次数"
    },
    {
     "expr": "node_filefd_maximum{instance=~\"$Node_name\"}",
     "legendFormat": "单个进程可以打开的最大文件描述符数量"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node_name\"} - node_memory_MemAvailable_bytes{instance=~\"$Node\"}",
     "legendFormat": "$host_ip-已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-可用"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-Free"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-Cached"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）5m",
   "type": "timeseries",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$Node_name\"}",
     "legendFormat": "$host_ip-TCP_alloc"
    }
   ]
  },
  {
   "title": "TCP 状态信息",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "node_tcp_connection_states{host_ip=~\"$host_ip\",state!~\"^tx_.*|^^rx_.*\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "每秒磁盘读写速度",
   "type": "timeseries",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_写入"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗费的时间",
   "type": "graph",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_每秒I/O操作"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）(beta)",
   "type": "graph",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$Node_name\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$Node_name\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_写入"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}"
    },
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$Node_name\"}[5m])",
     "legendFormat": "$host_ip-{{device}}_加权"
    }
   ]
  },
  {
   "title": "当前节点Pod总体资源使用信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "当前节点已分配资源（describe node）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\",node=~\"$Node_name\"})/sum(kube_node_status_allocatable{resource=\"cpu\",job=\"kube-state-metrics\",node=~\"$Node_name\"})*100",
     "legendFormat": "CPU Allocated By Node"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$Node_name\"})/sum(kube_node_status_allocatable{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$Node_name\"})*100",
     "legendFormat": "Memory Alllocated By Node"
    }
   ]
  },
  {
   "title": "当前node节点pod总体CPU使用率（kubectl top命令）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(sum((1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-discovery\",instance=~\"$Node_name\"}[5m])) by (instance))*100) by (instance))",
     "legendFormat": "$host_ip"
    }
   ]
  },
  {
   "title": "当前node节点pod总体内存使用率（kubectl top命令）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(sum((node_memory_Active_file_bytes{job=\"node-exporter-discovery\",instance=~\"$Node_name\"}+node_memory_Active_anon_bytes{job=\"node-exporter-discovery\",instance=~\"$Node_name\"}) / node_memory_MemTotal_bytes{job=\"node-exporter-discovery\",instance=~\"$Node_name\"}) by (instance)) *100",
     "legendFormat": "$host_ip"
    }
   ]
  },
  {
   "title": "Pod 总体Mem资源申请情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$Node_name\"}/1024/1024/1024)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$Node_name\"}/1024/1024/1024)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",job=\"kube-state-metrics\",node=~\"$Node_name\"}/1024/1024/1024)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "当前节点所有pod网络入流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{instance=~\"$host_ip:10250\",pod!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "当前节点所有pod网络出流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{instance=~\"$host_ip:10250\",pod!=\"\"}[2m]))by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "当前node节点所有pod 内存使用率（current/limits）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sum(container_memory_working_set_bytes{container!=\"\",container!=\"POD\",instance=~\"$host_ip:10250\"}) by (service,pod)) by (pod)/avg(sum(kube_pod_container_resource_limits{container!=\"\",container!=\"POD\",node=\"$Node_name\"}>0) by (service,pod)) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "当前node节点所有pod 内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (namespace,pod) (container_memory_usage_bytes{instance=~\"$host_ip:10250\",container!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "当前node节点所有Pod CPU使用率(current/limits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",instance=~\"$host_ip:10250\"}[2m])) by(container,pod)) by (pod)/sum(avg(kube_pod_container_resource_limits{container !=\"\",container!=\"POD\",resource=\"cpu\"}) by (container,pod)) by (pod)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}