{
 "title": "POD单体监控",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\",container=~\"$container\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pod QOS 信息",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\", pod=~\"$pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\",pod=~\"$pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\", pod=~\"$pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\",pod=~\"$pod\"}) by (pod,container)"
    }
   ]
  },
  {
   "title": "Pod CPU使用量(2m）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\",image!=\"\",pod=~\"$pod\",container!=\"\"}[2m])) by (pod,container)",
     "legendFormat": "Current: {{ pod }}——{{container}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\",container=~\"$container\"}) by (pod,container)",
     "legendFormat": "Working-set: {{ pod }}——{{container}}"
    },
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\", container!=\"POD\",container!=\"\",image!=\"\",container=~\"$container\"}) by (pod)",
     "legendFormat": "RSS : {{ pod }}"
    }
   ]
  },
  {
   "title": "pod 流出流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0\"}[5m])) by (pod)",
     "legendFormat": "TX：{{pod}}"
    }
   ]
  },
  {
   "title": "Pod 接收流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])) by (pod,interface)",
     "legendFormat": "{{pod}}---{{interface}}"
    }
   ]
  },
  {
   "title": "container 健康状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod,container)",
     "legendFormat": "{{pod}}——{{container}}"
    }
   ]
  },
  {
   "title": "Pod 重启次数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}——{{container}}"
    }
   ]
  },
  {
   "title": "container threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(container_threads{namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container)",
     "legendFormat": "{{pod}}——{{container}}"
    }
   ]
  },
  {
   "title": "container threads max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 56 },
   "targets": [
    {
     "expr": "avg(container_threads{namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\"}) by (pod,container)",
     "legendFormat": "{{pod}}——{{container}}"
    }
   ]
  }
 ]
}