{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "gpu", "query": { "query": "label_values(gpu)" } },
   {
    "name": "host_ip",
    "label": "host_ip",
    "query": {
     "query": "label_values(node_load1{nodetype=\"gpu\"},host_ip)"
    }
   },
   {
    "name": "Node_Name",
    "label": "Node_Name",
    "query": {
     "query": "label_values(node_load1{nodetype=\"gpu\",host_ip=~\"$host_ip\"},kubernetes_io_hostname)"
    }
   },
   {
    "name": "mode_name",
    "label": "mode_name",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$Node_Name\"}, modelName)"
    }
   },
   {
    "name": "task_ns",
    "label": "task_ns",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=~\"aijob.*|pipeline-system|service-system\"},namespace)"
    }
   },
   {
    "name": "task_code",
    "label": "task_code",
    "query": {
     "query": "label_values(kube_deployment_spec_replicas{namespace=~\"$task_ns\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "当前节点GPU相关资源使用率",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host_ip GPU 卡数 ",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(DCGM_FI_DEV_GPU_TEMP{kubernetes_node=~\"$Node_Name\"}) by (modelName)",
       "legendFormat": "总卡数-{{modelName}}"
      },
      {
       "expr": "count(DCGM_FI_DEV_GPU_TEMP{pod!=\"\",kubernetes_node=~\"$Node_Name\"}) by (modelName)",
       "legendFormat": "已用卡数-{{modelName}}"
      },
      {
       "expr": "count(DCGM_FI_DEV_GPU_TEMP{pod=\"\",kubernetes_node=~\"$Node_Name\"}) by (modelName)",
       "legendFormat": "未使用卡数-{{modelName}}"
      }
     ]
    },
    {
     "title": "算法Pod 所绑定的GPU 卡使用率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{pod!=\"\",kubernetes_node=~\"$Node_Name\"}",
       "legendFormat": "{{pod}}--gpu{{gpu}}"
      }
     ]
    },
    {
     "title": "$host_ip 所有GPU卡使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{kubernetes_node=~\"$Node_Name\"}",
       "legendFormat": "{{gpu}}"
      }
     ]
    },
    {
     "title": "$host_ip GPU卡显存使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_FB_USED{kubernetes_node=\"$Node_Name\"}) by (gpu) / (sum(DCGM_FI_DEV_FB_FREE{kubernetes_node=\"$Node_Name\"}) by (gpu) + sum(DCGM_FI_DEV_FB_USED{kubernetes_node=\"$Node_Name\"}) by(gpu)) *100",
       "legendFormat": "{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU 卡温度",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{kubernetes_node=~\"$Node_Name\"}",
       "legendFormat": "GPU - {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU 功率",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{kubernetes_node=~\"${Node_Name}\", gpu=~\"${gpu}\"}",
       "legendFormat": "GPU - {{gpu}}"
      }
     ]
    },
    {
     "title": "所有GPU主机GPU卡信息",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_GPU_TEMP) by (kubernetes_node,modelName)",
       "legendFormat": "gpu主机名与卡类型"
      },
      {
       "expr": "count(DCGM_FI_DEV_GPU_TEMP) by (kubernetes_node,modelName)",
       "legendFormat": "卡数量"
      },
      {
       "expr": "(sum(DCGM_FI_DEV_FB_FREE{}) by (kubernetes_node) + sum(DCGM_FI_DEV_FB_USED{}) by(kubernetes_node))",
       "legendFormat": "卡显存大小"
      }
     ]
    }
   ]
  },
  { "title": "集群总体GPU资源使用率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "  单个任务所有pod gpu使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod=~\"${task_code}.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "集群GPU卡型号及总数量",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL) by(modelName)",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "集群GPU卡总用量",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(DCGM_FI_DEV_GPU_UTIL{})", "legendFormat": "总卡数" },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{pod!=\"\"}) by (modelName)",
     "legendFormat": "已使用卡数--{{modelName}}"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL) by (modelName) - count(DCGM_FI_DEV_GPU_UTIL{pod!=\"\"}) by (modelName)",
     "legendFormat": "未使用卡数--{{modelName}}"
    }
   ]
  },
  {
   "title": "集群GPU卡型号及用量",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{}) by (modelName)"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{pod!=\"\"}) by (modelName)"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_TEMP{pod=\"\"}) by (modelName)"
    }
   ]
  },
  {
   "title": "集群 GPU总使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL) /count(DCGM_FI_DEV_GPU_UTIL{})/100",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "不同类型的GPU卡总使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL) by (modelName) /count(DCGM_FI_DEV_GPU_UTIL{}) by (modelName)/100",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "集群所有算法pod所绑定的gpu卡使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod!=\"\"}",
     "legendFormat": "{{pod}}---{{kubernetes_node}}---{{gpu}}"
    }
   ]
  },
  {
   "title": "集群所有算法pod所绑定的gpu卡显存使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{pod!=\"\"}) by (pod,gpu,kubernetes_node)/(sum(DCGM_FI_DEV_FB_FREE{}) by (pod,gpu,kubernetes_node) + sum(DCGM_FI_DEV_FB_USED{}) by(pod,gpu,kubernetes_node)) *100",
     "legendFormat": "{{pod}}---{{kubernetes_node}}---{{gpu}}"
    }
   ]
  },
  {
   "title": "Pod 使用gpu卡总览",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{pod!=\"\"}) by (modelName,pod,gpu,kubernetes_node)"
    },
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{pod!=\"\"}) by (pod,gpu,kubernetes_node,modelName)/(sum(DCGM_FI_DEV_FB_FREE{}) by (pod,gpu,kubernetes_node,modelName) + sum(DCGM_FI_DEV_FB_USED{}) by(modelName,pod,gpu,kubernetes_node)) *100"
    },
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{pod!=\"\"}+DCGM_FI_DEV_FB_FREE{pod!=\"\"}) by (gpu,modelName,pod,kubernetes_node)"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=~\"hook|default\"}[2m])) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",container=~\"hook|default\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"hook|default\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",container=~\"hook|default\"}) by (pod)"
    }
   ]
  },
  {
   "title": "所有gpu节点性能指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "所有gpu节点系统平均负载",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(node_load1{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}_1m"
      },
      {
       "expr": "avg(node_load5{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}_5m"
      },
      {
       "expr": "avg(node_load15{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}_15m"
      }
     ]
    },
    {
     "title": "所有gpu节点内存信息",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_MemTotal_bytes{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}-总内存"
      },
      {
       "expr": "avg(node_memory_MemTotal_bytes{nodetype=\"gpu\"} - node_memory_MemAvailable_bytes{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}-已用"
      },
      {
       "expr": "avg(node_memory_MemAvailable_bytes{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}--可用"
      },
      {
       "expr": "avg(node_memory_Buffers_bytes{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}--Buffers"
      },
      {
       "expr": "avg(node_memory_MemFree_bytes{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}--Free"
      },
      {
       "expr": "avg(node_memory_Cached_bytes{nodetype=\"gpu\"}) by (instance)",
       "legendFormat": "{{instance}}--Cached"
      }
     ]
    },
    {
     "title": "所有gpu节点cpu使用率",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\",nodetype=\"gpu\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\",nodetype=\"gpu\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\",nodetype=\"gpu\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\",nodetype=\"gpu\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-Iowait"
      },
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",nodetype=\"gpu\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}-Total"
      }
     ]
    },
    {
     "title": "所有gpu节点所有网卡出流量",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "avg(irate(node_network_transmit_bytes_total{job=\"node-exporter-discovery\",device!~\"lo|eth[2-5]|cali.*|tunl.*|kube.*\",nodetype=\"gpu\"}[30m])*8 )by (instance,device)",
       "legendFormat": "{{instance}}-{{device}}-流出"
      },
      {
       "expr": "-avg(irate(node_network_receive_bytes_total{job=\"node-exporter-discovery\",device!~\"lo|eth[2-5]|cali.*|tunl.*|kube.*\",nodetype=\"gpu\"}[30m])*8) by (instance,device)",
       "legendFormat": "{{instance}}---{{device}}"
      }
     ]
    },
    {
     "title": "所有gpu节点根分区分时磁盘使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "avg(1-(node_filesystem_free_bytes{device=~\"^/dev.*\",fstype=~\"ext4|xfs\",nodetype=\"gpu\",mountpoint=\"/\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\",nodetype=\"gpu\",mountpoint=\"/\"})) by (instance)",
       "legendFormat": "{{instance}}：{{mountpoint}}"
      }
     ]
    },
    {
     "title": "每次IO读写的耗时（参考：小于100ms）(beta)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_read_time_seconds_total{nodetype=\"gpu\"}[5m]) / irate(node_disk_reads_completed_total{nodetype=\"gpu\"}[5m])) by (instance,device)",
       "legendFormat": "{{instance}}-{{device}}_读取"
      },
      {
       "expr": "avg(irate(node_disk_write_time_seconds_total{nodetype=\"gpu\"}[5m]) / irate(node_disk_writes_completed_total{nodetype=\"gpu\"}[5m])) by (instance,device)",
       "legendFormat": "{{instance}}---{{device}}_写入"
      },
      {
       "expr": "avg(irate(node_disk_io_time_seconds_total{nodetype=\"gpu\"}[5m])) by (instance,device)",
       "legendFormat": "{{instance}}--{{device}}"
      },
      {
       "expr": "avg(irate(node_disk_io_time_weighted_seconds_total{nodetype=\"gpu\"}[5m])) by (instance,device)",
       "legendFormat": "{{instance}}-{{device}}_加权"
      }
     ]
    },
    {
     "title": "每秒磁盘读写速度",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total{nodetype=\"gpu\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}-{{device}}_读取"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total{nodetype=\"gpu\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}--{{device}}_写入"
      }
     ]
    },
    {
     "title": "磁盘读写速率（IOPS）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_reads_completed_total{nodetype=\"gpu\"}[30m])) by (instance,device)",
       "legendFormat": "{{instance}}--{{device}}"
      },
      {
       "expr": "avg(irate(node_disk_writes_completed_total{nodetype=\"gpu\"}[30m])) by (instance,device)",
       "legendFormat": "{{instance}}-{{device}}_写入"
      },
      {
       "expr": "avg(node_disk_io_now{nodetype=\"gpu\"}) by(instance)",
       "legendFormat": "{{instance}}-{{device}}_now"
      }
     ]
    },
    {
     "title": "每1秒内I/O操作耗费的时间",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_io_time_seconds_total{nodetype=\"gpu\"}[30m])) by (instance,device)",
       "legendFormat": "$host_ip-{{device}}_每秒I/O操作"
      }
     ]
    }
   ]
  }
 ]
}