{
 "title": "Higress Dashboard",
 "description": "Higress Ingress Controller Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMCLUSTER", "label": "vmcluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(envoy_server_live,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downstream Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(envoy_http_downstream_rq_total{namespace=\"$namespace\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Downstream Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{namespace=\"$namespace\", response_code_class!=\"5xx\"}[5m])) / sum(irate(envoy_http_downstream_rq_total{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Downstream Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_http_downstream_rq_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_http_downstream_rq_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_http_downstream_rq_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq_time_sum{namespace=\"$namespace\"}[1m])) / sum(irate(envoy_http_downstream_rq_time_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "TCP Received Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Upstream Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Upstream Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{namespace=\"$namespace\", cluster_name!~\"\\\\.internal$\",response_code_class!=\"5xx\"}[5m])) / sum(irate(envoy_cluster_upstream_rq{namespace=\"$namespace\", cluster_name!~\"\\\\.internal$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Upstream Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_cluster_upstream_rq_time_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\"}[1m])) / sum(irate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "TCP Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum(irate(container_cpu_usage_seconds_total{container=\"higress-gateway\", namespace=\"$namespace\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"higress-gateway\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}-envoy"
    },
    {
     "expr": "max(container_memory_working_set_bytes{container=\"discovery\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}-istio"
    },
    {
     "expr": "max(container_memory_working_set_bytes{container=\"higress-core\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}-core"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Downstream QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{namespace=\"$namespace\",http_conn_manager_prefix=~\"outbound_0.0.0.0_.*\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Upstream QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{namespace=\"$namespace\",cluster_name=~\"outbound.*\"}[1m])) by (response_code_class)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAF",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAF Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(irate(waf_filter_tx_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "qps"
      }
     ]
    },
    {
     "title": "WAF Denied by Phase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum(irate(waf_filter_tx_interruptions{namespace=\"$namespace\"}[1m])) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "WAF Denied by RuleID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "sum(irate(waf_filter_tx_interruptions{namespace=\"$namespace\"}[1m])) by (ruleid)",
       "legendFormat": "{{ruleid}}"
      }
     ]
    }
   ]
  },
  { "title": "XDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Envoy Details",
   "type": "graph",
   "description": "Shows details about Envoy proxies in the mesh",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "XDS Connections"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connection Failures"
    },
    {
     "expr": "sum(increase(envoy_server_hot_restart_epoch[1m]))",
     "legendFormat": "Envoy Restarts"
    }
   ]
  },
  {
   "title": "XDS Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\",namespace=\"$namespace\"})",
     "legendFormat": "XDS Active Connections"
    }
   ]
  },
  {
   "title": "XDS Requests Size",
   "type": "graph",
   "description": "Shows the size of XDS requests and responses",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "XDS Response Bytes Max"
    },
    {
     "expr": "quantile(0.5, rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Response Bytes Average"
    },
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Request Bytes Max"
    },
    {
     "expr": "quantile(.5, rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Request Bytes Average"
    }
   ]
  },
  { "title": "Service Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "QPS Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(irate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\", cluster_name!=\"xds-grpc\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\"}[5m])) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Requests Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(irate(envoy_cluster_upstream_rq{response_code_class=~\"(4|5)xx\",namespace=\"$namespace\", cluster_name!=\"xds-grpc\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\"}[5m])) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connection Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(envoy_cluster_upstream_cx_active{namespace=\"$namespace\", cluster_name!=\"xds-grpc\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\"}) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RT Top 10(Slow)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(irate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\", cluster_name!=\"xds-grpc\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\"}[5m])) by (cluster_name) / sum(irate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",cluster_name!=\"xds-grpc\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\"}[5m])) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound_([0-9]+)_(.*)_(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}